name: Validate Go

on:
  pull_request:
    branches: [dev, main]

jobs:
  go_lint:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Golangci-lint
      uses: golangci/golangci-lint-action@v6.0.1

  go_test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5

    - name: Test with the Go CLI
      run: go test -v ./...
